// Command bundle-tileset embeds a PNG into cmd/resources as a Go byte slice.
// It replaces the old `fyne bundle` step now that the game renders with Ebiten.
//
// Usage: go run ./scripts/bundle-tileset <input.png> <output.go>
package main

import (
	"fmt"
	"os"
	"strconv"
)

const header = `// auto-generated
// Code generated by '$ make assets' (scripts/bundle-tileset). DO NOT EDIT.

package resources

var tilesetPNGData = []byte(`

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: bundle-tileset <input.png> <output.go>")
		os.Exit(2)
	}
	data, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", os.Args[1], err)
		os.Exit(1)
	}
	out := header + strconv.Quote(string(data)) + ")\n"
	if err := os.WriteFile(os.Args[2], []byte(out), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", os.Args[2], err)
		os.Exit(1)
	}
}
