// Command build-tileset64 assembles the 64px game tileset from the mockup art.
//
// Sources:
//   - assets/mockups/terrain-192.png: 6x2 terrain tiles at 192px (3x of 64)
//   - assets/mockups/ships-192.png:   6 north-facing ships at 192px
//   - assets/pirate-wars-tileset.png: the old 32px sheet, upscaled 2x for the
//     rows the mockups do not cover (pennants, wake, examine ring, marker)
//
// Output: assets/pirate-wars-tileset-64.png, same 6x14 grid layout as the old
// sheet so none of the tile coordinates in cmd/resources change.
//
// The mockup ships carry an opaque navy backdrop and some terrain tiles a white
// one; both are flood-filled to transparency from the borders. Land features
// keyed out this way are composited back over the grass base tile. The eight
// ship facings are generated by rotating the north sprite in 45° steps.
//
// Usage: go run ./scripts/build-tileset64
package main

import (
	"flag"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"math"
	"os"
)

const (
	srcTile = 192 // mockup tile edge
	outTile = 64  // game tile edge
	cols    = 6
	rows    = 16 // 14 inherited rows + 2 for the second coast frame
)

func main() {
	style := flag.String("style", "none", "grading style: none, harbor, retro, chart")
	outPath := flag.String("out", "assets/pirate-wars-tileset-64.png", "output sheet path")
	flag.Parse()
	opts, ok := styles[*style]
	if !ok {
		fatal(fmt.Errorf("unknown style %q", *style))
	}

	old := loadNRGBA("assets/pirate-wars-tileset.png")
	terr := loadNRGBA("assets/mockups/terrain-192.png")
	ships := loadNRGBA("assets/mockups/ships-192.png")

	// Start from the old sheet at 2x so rows 10-13 (coast, waves, examine
	// ring, player marker, pennants, wake) stay populated; the ones we can
	// rebuild from the new art are overwritten below. Two extra rows hold the
	// second coast-foam frame.
	out := image.NewNRGBA(image.Rect(0, 0, cols*outTile, rows*outTile))
	draw.Draw(out, out.Bounds(), upscale2x(old), image.Point{}, draw.Src)

	// --- Terrain rows 0-1 ---
	grass64 := downscale3(subTile(terr, 0, 0))
	for r := 0; r < 2; r++ {
		for c := 0; c < cols; c++ {
			t := subTile(terr, c, r)
			if hasWhiteBackdrop(t) {
				keyOutBackdrop(t, 34)
				overlay := downscale3(t)
				tile := cloneNRGBA(grass64)
				draw.Draw(tile, tile.Bounds(), overlay, image.Point{}, draw.Over)
				place(out, tile, c, r)
			} else {
				place(out, downscale3(t), c, r)
			}
		}
	}

	// Retune the three water tiles into one cohesive ramp before anything
	// derives from them (coast strips, wave frames all sample these pixels).
	if opts.waterTune {
		for i, tune := range waterTunes {
			t := extract64(out, i, 1)
			retune(t, tune)
			place(out, t, i, 1)
		}
	}

	// --- Ships rows 2-9: 8 facings by rotation, N=0 then 45° clockwise ---
	for c := 0; c < cols; c++ {
		s := subTile(ships, c, 0)
		keyOutBackdrop(s, 30)
		for f := 0; f < 8; f++ {
			place(out, downscale3(rotate45(s, f)), c, 2+f)
		}
	}

	// --- Coast tiles from the new beach + shallow water art ---
	beach64 := extract64(out, 1, 0)
	shallow64 := extract64(out, 2, 1)
	type coast struct {
		c, r       int
		n, e, s, w bool
	}
	for _, cs := range []coast{
		{0, 10, true, false, false, false}, // water north
		{1, 10, false, true, false, false}, // water east
		{2, 10, false, false, true, false}, // water south
		{3, 10, false, false, false, true}, // water west
		{4, 10, true, true, false, false},  // NE corner
		{5, 10, false, true, true, false},  // SE corner
		{0, 11, false, false, true, true},  // SW corner
		{1, 11, true, false, false, true},  // NW corner
	} {
		place(out, makeCoast(beach64, shallow64, cs.n, cs.e, cs.s, cs.w, 0), cs.c, cs.r)
		// Frame B four rows down: the waterline breathes in and out.
		place(out, makeCoast(beach64, shallow64, cs.n, cs.e, cs.s, cs.w, 2.6), cs.c, cs.r+4)
	}

	// Crisp UI chrome drawn at native 64px instead of upscaled 32px art.
	place(out, makeBrackets(2, 20, 4, color.NRGBA{R: 216, G: 184, B: 48, A: 255}), 4, 11)
	place(out, makeBrackets(4, 14, 3, color.NRGBA{R: 242, G: 247, B: 239, A: 255}), 5, 11)

	// --- Shallow-water wave frames 2 and 3: sparkle-twinkle variants ---
	frames := twinkleFrames(shallow64, 3)
	place(out, frames[1], 2, 11)
	place(out, frames[2], 3, 11)

	// --- Wake frames: churned foam, drawn fresh at 64px ---
	place(out, makeWake(0), 2, 13)
	place(out, makeWake(1), 3, 13)

	gradeSheet(out, opts)

	f, err := os.Create(*outPath)
	if err != nil {
		fatal(err)
	}
	defer f.Close()
	if err := png.Encode(f, out); err != nil {
		fatal(err)
	}
	fmt.Println("wrote", *outPath)
}

func fatal(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }

func loadNRGBA(path string) *image.NRGBA {
	f, err := os.Open(path)
	if err != nil {
		fatal(err)
	}
	defer f.Close()
	img, err := png.Decode(f)
	if err != nil {
		fatal(fmt.Errorf("%s: %w", path, err))
	}
	dst := image.NewNRGBA(img.Bounds())
	draw.Draw(dst, dst.Bounds(), img, img.Bounds().Min, draw.Src)
	return dst
}

func cloneNRGBA(src *image.NRGBA) *image.NRGBA {
	dst := image.NewNRGBA(src.Bounds())
	copy(dst.Pix, src.Pix)
	return dst
}

// subTile copies one 192px tile out of a mockup sheet.
func subTile(sheet *image.NRGBA, c, r int) *image.NRGBA {
	dst := image.NewNRGBA(image.Rect(0, 0, srcTile, srcTile))
	draw.Draw(dst, dst.Bounds(), sheet, image.Pt(c*srcTile, r*srcTile), draw.Src)
	return dst
}

// extract64 copies one placed 64px tile back out of the output sheet.
func extract64(sheet *image.NRGBA, c, r int) *image.NRGBA {
	dst := image.NewNRGBA(image.Rect(0, 0, outTile, outTile))
	draw.Draw(dst, dst.Bounds(), sheet, image.Pt(c*outTile, r*outTile), draw.Src)
	return dst
}

func place(out *image.NRGBA, tile *image.NRGBA, c, r int) {
	draw.Draw(out, image.Rect(c*outTile, r*outTile, (c+1)*outTile, (r+1)*outTile), tile, image.Point{}, draw.Src)
}

// upscale2x nearest-neighbour doubles the old 32px sheet.
func upscale2x(src *image.NRGBA) *image.NRGBA {
	b := src.Bounds()
	dst := image.NewNRGBA(image.Rect(0, 0, b.Dx()*2, b.Dy()*2))
	for y := 0; y < b.Dy()*2; y++ {
		for x := 0; x < b.Dx()*2; x++ {
			dst.SetNRGBA(x, y, src.NRGBAAt(b.Min.X+x/2, b.Min.Y+y/2))
		}
	}
	return dst
}

// downscale3 box-averages 3x3 blocks with alpha weighting: 192 -> 64.
func downscale3(src *image.NRGBA) *image.NRGBA {
	dst := image.NewNRGBA(image.Rect(0, 0, outTile, outTile))
	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			var r, g, b, a float64
			for dy := 0; dy < 3; dy++ {
				for dx := 0; dx < 3; dx++ {
					p := src.NRGBAAt(x*3+dx, y*3+dy)
					w := float64(p.A)
					r += float64(p.R) * w
					g += float64(p.G) * w
					b += float64(p.B) * w
					a += w
				}
			}
			if a == 0 {
				continue
			}
			dst.SetNRGBA(x, y, color.NRGBA{
				R: uint8(r/a + 0.5), G: uint8(g/a + 0.5), B: uint8(b/a + 0.5),
				A: uint8(a/9 + 0.5),
			})
		}
	}
	return dst
}

// hasWhiteBackdrop reports whether any corner of a mockup tile is near-white,
// meaning the feature was painted on a white page rather than on terrain.
func hasWhiteBackdrop(img *image.NRGBA) bool {
	b := img.Bounds()
	corners := []image.Point{
		{b.Min.X + 2, b.Min.Y + 2}, {b.Max.X - 3, b.Min.Y + 2},
		{b.Min.X + 2, b.Max.Y - 3}, {b.Max.X - 3, b.Max.Y - 3},
	}
	for _, p := range corners {
		c := img.NRGBAAt(p.X, p.Y)
		if c.R > 235 && c.G > 235 && c.B > 235 {
			return true
		}
	}
	return false
}

// keyOutBackdrop flood-fills the backdrop colour to transparency starting from
// every border pixel, using the corner pixels as the reference colour. Enclosed
// pockets of the backdrop colour (inside rigging, between rocks) survive.
func keyOutBackdrop(img *image.NRGBA, tol float64) {
	b := img.Bounds()
	w, h := b.Dx(), b.Dy()
	ref := img.NRGBAAt(b.Min.X, b.Min.Y)

	within := func(c color.NRGBA) bool {
		dr := float64(c.R) - float64(ref.R)
		dg := float64(c.G) - float64(ref.G)
		db := float64(c.B) - float64(ref.B)
		return math.Sqrt(dr*dr+dg*dg+db*db) <= tol
	}

	visited := make([]bool, w*h)
	var stack []image.Point
	push := func(x, y int) {
		if x < 0 || y < 0 || x >= w || y >= h || visited[y*w+x] {
			return
		}
		visited[y*w+x] = true
		if within(img.NRGBAAt(b.Min.X+x, b.Min.Y+y)) {
			stack = append(stack, image.Pt(x, y))
		}
	}
	for x := 0; x < w; x++ {
		push(x, 0)
		push(x, h-1)
	}
	for y := 0; y < h; y++ {
		push(0, y)
		push(w-1, y)
	}
	for len(stack) > 0 {
		p := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		img.SetNRGBA(b.Min.X+p.X, b.Min.Y+p.Y, color.NRGBA{})
		push(p.X+1, p.Y)
		push(p.X-1, p.Y)
		push(p.X, p.Y+1)
		push(p.X, p.Y-1)
	}
}

// rotate45 rotates a 192px sprite clockwise by facing*45° about its centre.
// Cardinal facings use exact pixel transposes; diagonals sample bilinearly with
// a slight shrink so the hull's corners stay inside the tile.
func rotate45(src *image.NRGBA, facing int) *image.NRGBA {
	switch facing {
	case 0:
		return cloneNRGBA(src)
	case 2, 4, 6:
		return rotateExact(src, facing/2)
	}

	const shrink = 0.95
	angle := float64(facing) * math.Pi / 4
	sin, cos := math.Sin(angle), math.Cos(angle)
	dst := image.NewNRGBA(src.Bounds())
	half := float64(srcTile) / 2
	for y := 0; y < srcTile; y++ {
		for x := 0; x < srcTile; x++ {
			// Inverse map: rotate dest point back by -angle, undo the shrink.
			dx := (float64(x) + 0.5 - half) / shrink
			dy := (float64(y) + 0.5 - half) / shrink
			sx := dx*cos + dy*sin + half
			sy := -dx*sin + dy*cos + half
			dst.SetNRGBA(x, y, bilinear(src, sx, sy))
		}
	}
	return dst
}

// rotateExact rotates by quarter turns clockwise (1=90°, 2=180°, 3=270°).
func rotateExact(src *image.NRGBA, quarters int) *image.NRGBA {
	dst := image.NewNRGBA(src.Bounds())
	n := srcTile
	for y := 0; y < n; y++ {
		for x := 0; x < n; x++ {
			var sx, sy int
			switch quarters {
			case 1:
				sx, sy = y, n-1-x
			case 2:
				sx, sy = n-1-x, n-1-y
			default:
				sx, sy = n-1-y, x
			}
			dst.SetNRGBA(x, y, src.NRGBAAt(sx, sy))
		}
	}
	return dst
}

// bilinear samples src at a fractional point with alpha-premultiplied weights.
func bilinear(src *image.NRGBA, fx, fy float64) color.NRGBA {
	x0 := int(math.Floor(fx - 0.5))
	y0 := int(math.Floor(fy - 0.5))
	wx := (fx - 0.5) - float64(x0)
	wy := (fy - 0.5) - float64(y0)

	var r, g, b, a float64
	for dy := 0; dy < 2; dy++ {
		for dx := 0; dx < 2; dx++ {
			x, y := x0+dx, y0+dy
			if x < 0 || y < 0 || x >= srcTile || y >= srcTile {
				continue
			}
			w := (1 - math.Abs(float64(dx)-wx)) * (1 - math.Abs(float64(dy)-wy))
			p := src.NRGBAAt(x, y)
			aw := w * float64(p.A)
			r += float64(p.R) * aw
			g += float64(p.G) * aw
			b += float64(p.B) * aw
			a += aw
		}
	}
	if a < 1 {
		return color.NRGBA{}
	}
	return color.NRGBA{
		R: uint8(r/a + 0.5), G: uint8(g/a + 0.5), B: uint8(b/a + 0.5),
		A: uint8(a + 0.5),
	}
}

// makeCoast builds a 64px shoreline tile: the beach with a wavy strip of
// shallow water along each flagged edge, separated by a foam line.
func makeCoast(beach, shallow *image.NRGBA, n, e, s, w bool, phase float64) *image.NRGBA {
	tile := cloneNRGBA(beach)
	foam := color.NRGBA{R: 244, G: 250, B: 252, A: 235}
	foam2 := color.NRGBA{R: 220, G: 240, B: 248, A: 150}

	// depth returns the wavy water depth along an edge at position t; phase
	// shifts the waterline so the two coast frames lap against the sand.
	depth := func(t int) int {
		return 13 + int(3.5*math.Sin(float64(t)*0.35+phase)+2*math.Sin(float64(t)*0.13+1.7+phase*0.6))
	}

	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			// Distance past the waterline; negative means dry sand.
			in := math.MinInt32
			if n {
				if d := depth(x) - y; d > in {
					in = d
				}
			}
			if s {
				if d := depth(x+17) - (outTile - 1 - y); d > in {
					in = d
				}
			}
			if w {
				if d := depth(y+9) - x; d > in {
					in = d
				}
			}
			if e {
				if d := depth(y+29) - (outTile - 1 - x); d > in {
					in = d
				}
			}
			switch {
			case in > 2:
				tile.SetNRGBA(x, y, shallow.NRGBAAt(x, y))
			case in == 2:
				tile.SetNRGBA(x, y, blendNRGBA(shallow.NRGBAAt(x, y), foam2))
			case in >= 0:
				tile.SetNRGBA(x, y, blendNRGBA(tile.NRGBAAt(x, y), foam))
			}
		}
	}
	return tile
}

func blendNRGBA(base, over color.NRGBA) color.NRGBA {
	a := float64(over.A) / 255
	return color.NRGBA{
		R: uint8(float64(over.R)*a + float64(base.R)*(1-a) + 0.5),
		G: uint8(float64(over.G)*a + float64(base.G)*(1-a) + 0.5),
		B: uint8(float64(over.B)*a + float64(base.B)*(1-a) + 0.5),
		A: 255,
	}
}

// makeWake draws a cluster of soft foam blobs for the trailing-water overlay.
// The two frames shuffle the blobs so the churn appears to roil.
func makeWake(frame int) *image.NRGBA {
	type blob struct{ x, y, r, a float64 }
	sets := [2][]blob{
		{{32, 32, 10, 150}, {22, 26, 7, 120}, {43, 38, 6, 110}, {30, 45, 6, 95}, {41, 21, 5, 105}},
		{{32, 33, 8, 135}, {24, 40, 7, 120}, {42, 25, 7, 110}, {20, 24, 5, 90}, {45, 43, 5, 100}},
	}
	img := image.NewNRGBA(image.Rect(0, 0, outTile, outTile))
	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			var a float64
			for _, bl := range sets[frame] {
				dx, dy := float64(x)-bl.x, float64(y)-bl.y
				d := math.Sqrt(dx*dx+dy*dy) / bl.r
				if d < 1 {
					// Smooth radial falloff; overlapping blobs accumulate.
					f := 1 - d*d
					a += bl.a * f * f
				}
			}
			if a > 210 {
				a = 210
			}
			if a > 4 {
				img.SetNRGBA(x, y, color.NRGBA{R: 240, G: 250, B: 255, A: uint8(a)})
			}
		}
	}
	return img
}

// makeBrackets draws four corner brackets with a dark outline: the examine
// ring and player marker, redrawn crisp at 64px.
func makeBrackets(inset, length, thick int, fill color.NRGBA) *image.NRGBA {
	img := image.NewNRGBA(image.Rect(0, 0, outTile, outTile))
	outline := color.NRGBA{R: 28, G: 33, B: 48, A: 210}
	max := outTile - 1
	set := func(x, y int, c color.NRGBA) {
		if x >= 0 && y >= 0 && x < outTile && y < outTile {
			img.SetNRGBA(x, y, c)
		}
	}
	corner := func(ox, oy, dx, dy int) {
		// One outline pass haloing the bracket, then the fill.
		for pass := 0; pass < 2; pass++ {
			c := outline
			grow := 1
			if pass == 1 {
				c = fill
				grow = 0
			}
			for i := -grow; i < length+grow; i++ {
				for t := -grow; t < thick+grow; t++ {
					set(ox+dx*i, oy+dy*t, c)
					set(ox+dx*t, oy+dy*i, c)
				}
			}
		}
	}
	corner(inset, inset, 1, 1)
	corner(max-inset, inset, -1, 1)
	corner(inset, max-inset, 1, -1)
	corner(max-inset, max-inset, -1, -1)
	return img
}

// twinkleFrames returns n variants of a water tile where the bright sparkle
// pixels fade in and out in rotating thirds, so the sea glitters instead of
// pulsing as one.
func twinkleFrames(base *image.NRGBA, n int) []*image.NRGBA {
	var lumSum, lumMax float64
	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			p := base.NRGBAAt(x, y)
			l := 0.299*float64(p.R) + 0.587*float64(p.G) + 0.114*float64(p.B)
			lumSum += l
			if l > lumMax {
				lumMax = l
			}
		}
	}
	mean := lumSum / (outTile * outTile)
	// Adaptive threshold: on a dark sea only the foam specks qualify; on the
	// bright shallow tile the lattice highlights do. A fixed offset from the
	// mean picks nothing at all on tiles that are bright overall.
	threshold := mean + math.Max(25, (lumMax-mean)*0.45)

	frames := make([]*image.NRGBA, n)
	for k := 0; k < n; k++ {
		frames[k] = cloneNRGBA(base)
	}
	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			p := base.NRGBAAt(x, y)
			lum := 0.299*float64(p.R) + 0.587*float64(p.G) + 0.114*float64(p.B)
			if lum < threshold {
				continue
			}
			group := (x/3 + y/3) % n
			for k := 0; k < n; k++ {
				// Each sparkle dims on the frame matching its group.
				if (group+k)%n != 0 {
					continue
				}
				f := 0.35
				frames[k].SetNRGBA(x, y, color.NRGBA{
					R: uint8(float64(p.R)*f + (1-f)*float64(p.R)*mean/lum),
					G: uint8(float64(p.G)*f + (1-f)*float64(p.G)*mean/lum),
					B: uint8(float64(p.B)*f + (1-f)*float64(p.B)*mean/lum),
					A: p.A,
				})
			}
		}
	}
	return frames
}

// ---------------------------------------------------------------------------
// Style grading
// ---------------------------------------------------------------------------

// styleOpts describes one grading recipe applied over the assembled sheet.
type styleOpts struct {
	waterTune bool    // pull the three waters into one cohesive ramp
	snap      float64 // 0..1 mix toward the master palette
	pixelate  bool    // average 2x2 blocks for a uniform chunky grain
	warm      bool    // paper-warm tint and mild desaturation
}

var styles = map[string]styleOpts{
	"none":   {},
	"harbor": {waterTune: true, snap: 0.75},
	"retro":  {waterTune: true, snap: 1.0, pixelate: true},
	"chart":  {waterTune: true, snap: 0.35, warm: true},
}

// waterTune retargets a tile's per-channel mean and squeezes its contrast.
type waterTuneSpec struct {
	target   [3]float64
	contrast float64
}

// Indexed by column in row 1: deep, open, shallow. The source tiles jump from
// saturated navy to neon cyan; these targets sit on one hue ramp so the three
// waters read as depths of the same sea.
var waterTunes = []waterTuneSpec{
	{target: [3]float64{24, 46, 92}, contrast: 0.95},
	{target: [3]float64{43, 80, 140}, contrast: 0.90},
	{target: [3]float64{105, 175, 185}, contrast: 0.80},
}

func retune(tile *image.NRGBA, spec waterTuneSpec) {
	var mean [3]float64
	n := float64(outTile * outTile)
	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			p := tile.NRGBAAt(x, y)
			mean[0] += float64(p.R)
			mean[1] += float64(p.G)
			mean[2] += float64(p.B)
		}
	}
	for i := range mean {
		mean[i] /= n
	}
	for y := 0; y < outTile; y++ {
		for x := 0; x < outTile; x++ {
			p := tile.NRGBAAt(x, y)
			tile.SetNRGBA(x, y, color.NRGBA{
				R: clamp8(spec.target[0] + (float64(p.R)-mean[0])*spec.contrast),
				G: clamp8(spec.target[1] + (float64(p.G)-mean[1])*spec.contrast),
				B: clamp8(spec.target[2] + (float64(p.B)-mean[2])*spec.contrast),
				A: p.A,
			})
		}
	}
}

func clamp8(v float64) uint8 {
	if v < 0 {
		return 0
	}
	if v > 255 {
		return 255
	}
	return uint8(v + 0.5)
}

// masterPalette is the curated colour set every style leans on: sea ramp,
// lagoon, sand and soil, greens, rock, roofs, hull browns, sail cream, flag
// accents. Snapping mixed-source art toward one palette is what makes the
// sheet read as a single hand.
var masterPalette = parsePalette(
	"0d1b33", "1a2f5e", "16306e", "2a5397", "3a6bb0", "4f86c4",
	"5fa8b8", "62aebf", "7cc4cd", "a5dde2",
	"d8eef0", "f2f7ef", "ffffff",
	"efd9a0", "dcbd7c", "bf9a5e", "96703f", "63472a",
	"89b83e", "62961f", "3f7317", "2c5410", "8fce55",
	"27501e", "3a7028",
	"c9b06a", "a08b4e",
	"c9c9c2", "989891", "6d6d66", "45453f",
	"a83a30", "c85a42", "7c2820", "d87f52",
	"c07838", "8f5426",
	"3a8a8c", "2a6466",
	"8a5a2e", "6b4220", "4a2c14", "a87844",
	"e8dcc0", "c9b896",
	"d8b830", "2f6ec0", "2f8a3a", "c03028",
	"1c2130",
)

func parsePalette(hexes ...string) [][3]float64 {
	pal := make([][3]float64, len(hexes))
	for i, h := range hexes {
		var r, g, b int
		fmt.Sscanf(h, "%02x%02x%02x", &r, &g, &b)
		pal[i] = [3]float64{float64(r), float64(g), float64(b)}
	}
	return pal
}

// nearestPalette picks the closest master colour by redmean distance.
func nearestPalette(r, g, b float64) [3]float64 {
	best := masterPalette[0]
	bestD := math.MaxFloat64
	for _, c := range masterPalette {
		rm := (r + c[0]) / 2
		dr, dg, db := r-c[0], g-c[1], b-c[2]
		d := (2+rm/256)*dr*dr + 4*dg*dg + (2+(255-rm)/256)*db*db
		if d < bestD {
			bestD = d
			best = c
		}
	}
	return best
}

// gradeSheet applies the style's global pass over every pixel of the sheet.
func gradeSheet(img *image.NRGBA, opts styleOpts) {
	b := img.Bounds()
	if opts.snap > 0 || opts.warm {
		for y := b.Min.Y; y < b.Max.Y; y++ {
			for x := b.Min.X; x < b.Max.X; x++ {
				p := img.NRGBAAt(x, y)
				if p.A == 0 {
					continue
				}
				r, g, bl := float64(p.R), float64(p.G), float64(p.B)
				if opts.warm {
					// Paper-warm tint with a touch of desaturation, echoing
					// the watercolour title art.
					lum := 0.299*r + 0.587*g + 0.114*bl
					const ds = 0.18
					r = (r*(1-ds) + lum*ds) * 1.06
					g = g*(1-ds) + lum*ds
					bl = (bl*(1-ds) + lum*ds) * 0.90
				}
				if opts.snap > 0 {
					c := nearestPalette(r, g, bl)
					r = r*(1-opts.snap) + c[0]*opts.snap
					g = g*(1-opts.snap) + c[1]*opts.snap
					bl = bl*(1-opts.snap) + c[2]*opts.snap
				}
				img.SetNRGBA(x, y, color.NRGBA{R: clamp8(r), G: clamp8(g), B: clamp8(bl), A: p.A})
			}
		}
	}
	if opts.pixelate {
		// Uniform 2px grain: the mixed sources land on one pixel grid, which
		// hides their differing levels of detail.
		for y := b.Min.Y; y < b.Max.Y; y += 2 {
			for x := b.Min.X; x < b.Max.X; x += 2 {
				var r, g, bl, a float64
				for dy := 0; dy < 2; dy++ {
					for dx := 0; dx < 2; dx++ {
						p := img.NRGBAAt(x+dx, y+dy)
						w := float64(p.A)
						r += float64(p.R) * w
						g += float64(p.G) * w
						bl += float64(p.B) * w
						a += w
					}
				}
				var out color.NRGBA
				if a > 0 {
					out = color.NRGBA{
						R: uint8(r/a + 0.5), G: uint8(g/a + 0.5), B: uint8(bl/a + 0.5),
						A: uint8(a/4 + 0.5),
					}
				}
				for dy := 0; dy < 2; dy++ {
					for dx := 0; dx < 2; dx++ {
						img.SetNRGBA(x+dx, y+dy, out)
					}
				}
			}
		}
	}
}
